#数据预处理配置
IMG_PATH='../common/dataset/'
IMG_HEIGHT=68
IMG_WIDTH=68

#随机性和数据集划分
SEED=42
TRAIN_SIZE=0.75
TEST_SIZE=0.25
NOISE_FACTOR=0.5

#相关超参数
LEARNING_RATE=0.001
EPOCHS=20
TRAIN_BATCH_SIZE=128
TEST_BATCH_SIZE=128

#模块名称和保存模型参数的文件
PROJECT_PACKAGE_NAME='ITH'
DENOISER_MODEL_NAME='denoiser.pt'